# .github/workflows/docker-publish.yml

name: Build and Publish Docker Image

on:
  push:
    branches:
      - master  # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t darkchocolate77/christmas-community:latest .

    - name: Push Docker image
      run: docker push darkchocolate77/christmas-community:latest
