# .github/workflows/docker-publish.yml

name: Build and Publish Docker Image

on:
  push:
    branches:
      - master  # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image for ARM
      run: |
        docker buildx build --platform linux/arm/v7,linux/arm64 \
            -t darkchocolate77/christmas-community:latest \
            --build-arg NPM_TIMEOUT=10000 \
            --push .
